services:
  - type: web
    name: laravel-react-portfolio
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_KEY
        value: "base64:362qZ15Hr9WoPvZVlx/kMwn/3iw+5g8+JSYLGe/E+eI="
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: "https://laravel-react-portfolio.onrender.com"
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: stderr
